# Settings
# $_Б__ы__р_Н_ы_Е__ш_А_Р_и_К_и_
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Versions
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

## Mod Info
mod_id=salo2b
mod_name=beer
mod_license=MIT
mod_version=0.0.1
mod_group_id=salo2b.beer
mod_authors=salo2b
mod_description=sosalzapivo
